//    Copyright 2019-2022 namazso <admin@namazso.eu>
//    This file is part of OpenHashTab.
//
//    OpenHashTab is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    OpenHashTab is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with OpenHashTab.  If not, see <https://www.gnu.org/licenses/>.

// This file will be processed by the MIDL tool to
// produce the type library (OpenHashTab.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(50b2e14f-21c8-4a3c-9a25-3d3356178549),
	pointer_default(unique)
]
interface IOpenHashTabShlExt : IUnknown
{
};
[
	uuid(715dae2b-0063-4d88-8f94-3dc072fc3fb0),
	version(1.0),
]
library OpenHashTabLib
{
	importlib("stdole2.tlb");
	[
		uuid(23b5bdd4-7669-42b8-9cdc-beebc8a5baa9)
	]
	coclass OpenHashTabShlExt
	{
		[default] interface IOpenHashTabShlExt;
	};
};

import "shobjidl.idl";
