#define IDC_ALGORITHM_LIST                       200
#define IDC_BUTTON_CANCEL                        201
#define IDC_BUTTON_CHECK_FOR_UPDATES             202
#define IDC_BUTTON_CLIPBOARD                     203
#define IDC_BUTTON_EXPORT                        204
#define IDC_BUTTON_SETTINGS                      205
#define IDC_BUTTON_VT                            206
#define IDC_CHECK_CHECKAGAINST_AUTOFORMAT        207
#define IDC_CHECK_CHECKAGAINST_STRICT            208
#define IDC_CHECK_CLIPBOARD_AUTOENABLE           209
#define IDC_CHECK_CLIPBOARD_AUTOENABLE_EXCLUSIVE 210
#define IDC_CHECK_CLIPBOARD_AUTOENABLE_IF_NONE   211
#define IDC_CHECK_DISPLAY_UPPERCASE              212
#define IDC_CHECK_HASH_SUMFILE_TOO               213
#define IDC_CHECK_LOOK_FOR_SUMFILES              214
#define IDC_CHECK_SUMFILE_ALGORITHM_ONLY         215
#define IDC_CHECK_SUMFILE_BANNER                 216
#define IDC_CHECK_SUMFILE_BANNER_DATE            217
#define IDC_CHECK_SUMFILE_DOT_HASH_COMPATIBLE    218
#define IDC_CHECK_SUMFILE_FORWARD_SLASHES        219
#define IDC_CHECK_SUMFILE_UNIX_ENDINGS           220
#define IDC_CHECK_SUMFILE_UPPERCASE              221
#define IDC_CHECK_SUMFILE_USE_DOUBLE_SPACE       222
#define IDC_COMBO_EXPORT                         223
#define IDC_EDIT_HASH                            224
#define IDC_ERROR_BG_BTN                         225
#define IDC_ERROR_BG_CHECK                       226
#define IDC_ERROR_FG_BTN                         227
#define IDC_ERROR_FG_CHECK                       228
#define IDC_ERROR_GROUP                          229
#define IDC_ERROR_SAMPLE                         230
#define IDC_HASH_LIST                            231
#define IDC_ICON_1                               232
#define IDC_INSECURE_BG_BTN                      233
#define IDC_INSECURE_BG_CHECK                    234
#define IDC_INSECURE_FG_BTN                      235
#define IDC_INSECURE_FG_CHECK                    236
#define IDC_INSECURE_GROUP                       237
#define IDC_INSECURE_SAMPLE                      238
#define IDC_MATCH_BG_BTN                         239
#define IDC_MATCH_BG_CHECK                       240
#define IDC_MATCH_FG_BTN                         241
#define IDC_MATCH_FG_CHECK                       242
#define IDC_MATCH_GROUP                          243
#define IDC_MATCH_SAMPLE                         244
#define IDC_MISMATCH_BG_BTN                      245
#define IDC_MISMATCH_BG_CHECK                    246
#define IDC_MISMATCH_FG_BTN                      247
#define IDC_MISMATCH_FG_CHECK                    248
#define IDC_MISMATCH_GROUP                       249
#define IDC_MISMATCH_SAMPLE                      250
#define IDC_PROGRESS                             251
#define IDC_PROJECT_LINK                         252
#define IDC_PROJECT_NAME                         253
#define IDC_STATIC_CHECK_AGAINST                 254
#define IDC_STATIC_CHECK_RESULT                  255
#define IDC_STATIC_EXPORT_TO                     256
#define IDC_STATIC_PROCESSING                    257
#define IDC_STATIC_SUMFILE                       258
#define IDC_UNKNOWN_BG_BTN                       259
#define IDC_UNKNOWN_BG_CHECK                     260
#define IDC_UNKNOWN_FG_BTN                       261
#define IDC_UNKNOWN_FG_CHECK                     262
#define IDC_UNKNOWN_GROUP                        263
#define IDC_UNKNOWN_SAMPLE                       264
#define IDC_CHECK_DISPLAY_MONOSPACE              265
#define IDC_BUTTON_SUMMARY                       266

#define IDD_OPENHASHTAB_PROPPAGE 300
#define IDD_SETTINGS             301

#define IDI_ICON1    310
#define IDI_ICON_COG 311
#define IDI_ICON_VT  312
#define IDI_ICON_SUM 313

#define IDM_COPY_EVERYTHING 320
#define IDM_COPY_FILE       321
#define IDM_COPY_HASH       322
#define IDM_COPY_LINE       323

#define IDS_ALGORITHM                      400
#define IDS_BACKGROUND                     401
#define IDS_CANCEL                         402
#define IDS_CHECKAGAINST_AUTOFORMAT        403
#define IDS_CHECKAGAINST_STRICT            404
#define IDS_CHECK_AGAINST                  405
#define IDS_CHECK_FOR_UPDATES              406
#define IDS_CLIPBOARD                      407
#define IDS_CLIPBOARD_AUTOENABLE           408
#define IDS_CLIPBOARD_AUTOENABLE_EXCLUSIVE 409
#define IDS_CLIPBOARD_AUTOENABLE_IF_NONE   410
#define IDS_COPIED                         411
#define IDS_COPY_EVERYTHING                412
#define IDS_COPY_FILE                      413
#define IDS_COPY_HASH                      414
#define IDS_COPY_LINE                      415
#define IDS_DISPLAY_UPPERCASE              416
#define IDS_DONE                           417
#define IDS_ERROR                          418
#define IDS_ERROR_GROUP                    419
#define IDS_EXPORT_BTN                     420
#define IDS_EXPORT_TO                      421
#define IDS_FILENAME                       422
#define IDS_FOREGROUND                     423
#define IDS_HASH                           424
#define IDS_HASHES                         425
#define IDS_HASH_SUMFILE_TOO               426
#define IDS_INSECURE_GROUP                 427
#define IDS_ITEMS_MATCHING                 428
#define IDS_ITEM_MATCHING                  429
#define IDS_LOOK_FOR_SUMFILES              430
#define IDS_MATCH_GROUP                    431
#define IDS_MISMATCH_GROUP                 432
#define IDS_NOMATCH                        433
#define IDS_PROCESSING                     434
#define IDS_SETTINGS_TITLE                 435
#define IDS_SUMFILE                        436
#define IDS_SUMFILE_ALGORITHM_ONLY         437
#define IDS_SUMFILE_BANNER                 438
#define IDS_SUMFILE_BANNER_DATE            439
#define IDS_SUMFILE_DOT_HASH_COMPATIBLE    440
#define IDS_SUMFILE_FORWARD_SLASHES        441
#define IDS_SUMFILE_UNIX_ENDINGS           442
#define IDS_SUMFILE_UPPERCASE              443
#define IDS_SUMFILE_USE_DOUBLE_SPACE       444
#define IDS_UNKNOWN_GROUP                  445
#define IDS_UPDATE_AVAILABLE_TEXT          446
#define IDS_UPDATE_AVAILABLE_TITLE         447
#define IDS_UPDATE_DISABLED_IN_DEV_BUILD   448
#define IDS_UPDATE_NEWEST_TEXT             449
#define IDS_UPDATE_NEWEST_TITLE            450
#define IDS_VT_NOT_FOUND                   451
#define IDS_VT_NO_COMPATIBLE               452
#define IDS_DISPLAY_MONOSPACE              453
#define IDS_SUMMARY                        454
